name: Deploy Laravel Application

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy files to server
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        set -x  # Enable debugging
        rsync -avz --exclude '.git' --exclude 'node_modules' --exclude '.github' ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/www/kailashgroupdemo.bivekp18.sg-host.com
